import Nav from './components/Nav';
import './globals.css';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import Hydrate from './components/Hydrate';
import { Roboto, Lobster_Two } from 'next/font/google';

// Defind main font
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin-ext'],
  variable: '--font-roboto'
});

const lobster = Lobster_Two({
  weight: ['700'],
  subsets: ['latin'],
  variable: '--font-lobster'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  // Fetch user
  const session = await getServerSession(authOptions);
  return (
    <html data-theme="light" className={`${roboto.variable} ${lobster.variable}`}>
      <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string} />
        {children}
      </Hydrate>
    </html>
  );
}
